### ISSUE TITLE
As a user, I will be able to add general events into my app, so that I can plan for general events. 

### ISSUE THREAD

**Issue by markuz5116** [AY2021S2-CS2103T-W15-1/tp#137]

**Comment by markuz5116** [comment]
add, edit, clear, find, delete

**Comment by jellymias** [comment]
i can do the event skeleton, add and edit

**Comment by maikongeh** [comment]
I can do general event done and delete

GE attributes, String description, LocalDateTime 
general event description prefix - g/
general event LDT prefix - on/

**Comment by markuz5116** [comment]
I can do clear and find

**Comment by markuz5116** [comment]
> I can do clear, find and generaleventlist

clear and generaleventlist are done.
